name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/dannybarrientosagudelo/dannybarrientosagudelo
            azure-pipeline-name: 'swaglabs-serenity-cucumber-CI-'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }} 
        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
              distribution: 'zulu'
              java-version: '17'
        - name: Build with Gradle
             run: gradle clean test
        
